version: '3'

services:

  # https://hub.docker.com/r/mysql/mysql-server/
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine

  web:
    image: rikeda71/privateschoolwebapp:latest
    command: sh -c "sleep 3; ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    image: rikeda71/privateschoolwebapp:latest
    command: celery -A project worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    image: rikeda71/privateschoolwebapp:latest
    command: celery -A project beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
volumes:
  db-datadir: