# Generated by Django 2.1.1 on 2018-10-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pdffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='title',
        ),
    ]
