# Generated by Django 2.1.1 on 2018-10-08 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_pdffile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(verbose_name='日付')),
                ('segment', models.CharField(max_length=1, verbose_name='コマ')),
                ('student_name', models.CharField(max_length=10, verbose_name='生徒名')),
                ('subject_name', models.CharField(max_length=10, verbose_name='教科名')),
                ('student_grade', models.CharField(max_length=10, verbose_name='学年')),
                ('pdf_id', models.ForeignKey(on_delete=True, related_name='pdf', to='accounts.PDFFile')),
                ('user_id', models.ForeignKey(on_delete=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
