# Generated by Django 2.1.2 on 2018-10-14 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181008_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
